services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__WEBSERVER__SECRET_KEY: secret
    volumes:
      - ./cases:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
        airflow webserver
      "

  scheduler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    volumes:
      - ./cases:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: airflow scheduler

  worker:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    volumes:
      - ./cases:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: airflow celery worker

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: data-engineer-portfolio-clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"   # HTTP API (для dbt)
      - "9000:9000"   # Native protocol (для клиентов)
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-config/users.d:/etc/clickhouse-server/users.d 
    environment:
      CLICKHOUSE_DB: real_estate
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
  clickhouse-data: