CREATE TABLE IF NOT EXISTS raw_secondary_market (
    id String,
    date_posted Date,
    district String,
    okrug String,
    lat Float64,
    lon Float64,
    total_area Float64,
    living_area Float64,
    kitchen_area Float64,
    rooms Int32,
    floor Int32,
    total_floors Int32,
    building_year Int32,
    building_type String,
    ceiling_height Float64,
    has_balcony Bool,
    renovation String,
    metro_station String,
    metro_line String,
    metro_distance_min Int32,
    metro_distance_type String,
    to_center_km Float64,
    price_rub Int64,
    price_per_sqm Int32,
    mortgage_rate_at_listing Float64,
    seller_type String
) ENGINE = MergeTree()
ORDER BY id