select
    id as listing_id,
    date_posted,
    district,
    okrug,
    lat,
    lon,
    total_area,
    living_area,
    kitchen_area,
    rooms,
    floor,
    total_floors,
    building_year,
    building_type,
    ceiling_height,
    has_balcony,
    renovation,
    metro_station,
    metro_line,
    metro_distance_min,
    metro_distance_type,
    to_center_km,
    price_rub,
    price_per_sqm,
    mortgage_rate_at_listing,
    seller_type,
    now() as _loaded_at
from {{ source('raw', 'raw_secondary_market') }}
where price_rub > 0 and total_area > 0
