select
    id as listing_id,
    date_posted,
    complex_id,
    complex_name,
    developer,
    complex_class,
    district,
    okrug,
    lat,
    lon,
    total_area,
    rooms,
    floor,
    total_floors,
    completion_year,
    ready_status,
    metro_station,
    metro_line,
    metro_distance_min,
    to_center_km,
    price_rub,
    price_per_sqm,
    deal_type,
    subsidized_mortgage,
    mortgage_rate_at_listing,
    now() as _loaded_at
from {{ source('raw', 'raw_new_builds') }}
where price_rub > 0 and total_area > 0
